### ISSUE TITLE
missing files in fresh installation

### ISSUE THREAD

**Issue by ghost** [pinax/pinax-projects#49]
after installing pinax as described [here](http://pinaxproject.com/pinax/quick_start/) I started the server and I got the following errors:

[13/Sep/2017 14:11:26] "GET /account/login/ HTTP/1.1" 200 4570
[13/Sep/2017 14:11:26] "GET /site_media/static/css/app.css HTTP/1.1" 404 1668
[13/Sep/2017 14:11:26] "GET /site_media/static/pinax/js/theme.js HTTP/1.1" 304 0
[13/Sep/2017 14:11:26] "GET /site_media/static/js/site.js HTTP/1.1" 404 1665

**Comment by paltman** [comment]
Sorry, that documentation has gotten out of date. :/

Please use the `pinax-cli` as described here: http://pinaxproject.com/pinax/pinax_starter_projects/

There is currently some in progress work on that branch and the pinax command line will let you get last working version.

**Comment by ghost** [comment]
Thanks
I followed the instructions in that page for project project social-auth 
I got the same errors. 

[15/Sep/2017 08:15:55] "GET /site_media/static/js/site.js HTTP/1.1" 404 1665
[15/Sep/2017 08:15:55] "GET /site_media/static/pinax/js/theme.js HTTP/1.1" 304 0
[15/Sep/2017 08:15:55] "GET /site_media/static/css/app.css HTTP/1.1" 404 1668
[15/Sep/2017 08:15:55] "GET /site_media/static/js/site.js HTTP/1.1" 404 1665

**Comment by roperi** [comment]
Me too,  @jucajuca but for the 'account' project.  :(

```
[29/Dec/2017 18:07:54] "GET /site_media/static/css/app.css HTTP/1.1" 404 1668
[29/Dec/2017 18:07:54] "GET /site_media/static/js/site.js HTTP/1.1" 404 1665
```

**Comment by milven-domingos** [comment]
im getting the same error too

**Comment by milven-domingos** [comment]
please can anyone help me

**Comment by KatherineMichel** [comment]
@milven-domingos This is something that needs to be fixed. In the meantime, I know that someone who had a similar problem located those files in a different folder (/static/dist in his case) and moved them to /site_media/static and that fixed the problem.

**Comment by paltman** [comment]
@jucajuca @h-2-0 @milven-domingos you guys are getting 404s after running `npm run dev` and opening http://localhost:3000/ in your browser?

**Comment by paltman** [comment]
It almost sounds like you are running with `DEBUG = False` and haven't run `collectstatic`

**Comment by rich-in-dallas** [comment]
I am also having the same issue. All configurations are looking for the app.css and the site.js
I ran collectstatic;however, still no:
/site_media/static/js/site.js
/site_media/static/css/app.css

**Comment by zahidaliyounis** [comment]
Please try the following commands in order:

npm install
npm run build
./manage.py collect static

Then run server as usual

**Comment by liutianfang** [comment]
same error

what project or module  these two file belong?  I can not find it in pinax projects

**Comment by ghost** [comment]
@paltman 
The solution of @zahidaliyounis should be added to the documentation. (or to the install script.)

npm install
npm run build
./manage.py collectstatic
 
There wa a typo, correct command is collectstatic (no space)

**Comment by paltman** [comment]
the solution is really:

pip install -r requirements.txt
npm install
./manage.py migrate
npm run dev

which is already in the README

**Comment by paltman** [comment]
The instructions should be the README of the project started using any of the templates in this repo.

You can find a copy of these instructions here:

https://github.com/pinax/pinax-starter-projects/tree/account#getting-started

Is this not working for anyone?

You should not be running `collectstatic` or moving static files around manually for local development.

**Comment by KatherineMichel** [comment]
I believe this issue can be closed bc/guidance now update to date in both README and main docs.
