### ISSUE TITLE
Error in the process of installation [SSL certificate]

### ISSUE THREAD

**Issue by MarkLouren** [pinax/pinax-projects#75]
Hello couldn't install the Pinax using this guide: https://pinaxproject.com/pinax/quick_start/
After typing:  pip install pinax-cli I receive this error:

Error: couldn't download URL https://github.com/pinax/pinax-starter-projects/archive/account-4.0.4.tar.gz to account-4.0.4.tar.gz: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>

How is it possible to solve it?

**Comment by KatherineMichel** [comment]
I do not have that problem when I install a project. Unfortunately, I think it has to do with certificate verification through your computer. There is not a simple solution that I can see though. If you Google the error, there are some conversations about what to do, such as this one: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by MarkLouren** [comment]
oh, thanks for the explanation. I thought it's a common problem. I'll check solutions.
